{% set name = "sequencetools" %}
{% set version = "1.4.0" %}
{% set md5 = "af9f4df893bd0047ef10cbae30846bb0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/stschiff/sequenceTools/archive/v{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 1
  skip: True  #  [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - stack >=1.7.1
    - zlib
    - wget
    - gmp
    - perl 
    - xz
  run:
    - zlib
    - xz
    - gmp
    - samtools

test:
  commands:
    - pileupCaller --version

about:
  home: https://github.com/stschiff/sequenceTools
  license: MIT
  summary: Tools for population genetics on sequencing datas
