{% set name = "sequencetools" %}
{% set version = "1.4.0.5" %}
{% set md5 = "399df2fcea0a6cb0d4f5cb1e6b4b67bc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/gitter-bioinf/sequenceTools/releases/download/v{{ version }}-test/sequencetools_static.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  skip: True # [osx]
  binary_relocation: False

requirements:
  run:
    - zlib
    - xz
    - gmp
    - samtools

test:
  commands:
    - pileupCaller --version

about:
  home: https://github.com/stschiff/sequenceTools
  license: MIT
  summary: Tools for population genetics on sequencing datas
